services:
  db:
    image: postgres:15-alpine
    container_name: stayflow-db
    environment:
      POSTGRES_DB: stayflow_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5444:5432" # Porta externa 5444 para evitar conflitos
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
